
[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/*"
  function = "seo"

[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"

[[edge_functions]]
  path = "/robots.txt"
  function = "robots"
