
[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  path = "/robots.txt"
  function = "robots"

[[edge_functions]]
  path = "/sitemap.xml"
  function = "sitemap"

[[edge_functions]]
  path = "/*"
  function = "seo"

# SPA redirect rule - must come after edge functions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Sitemap plugin
[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"

