-- Update WordPress content
UPDATE software 
SET 
  description = 'WordPress powers over 40% of the web and excels at programmatic SEO with its extensive plugin ecosystem, flexible theming system, and robust content management capabilities. Perfect for creating thousands of SEO-optimized pages automatically through custom post types, automated content generation, and advanced SEO plugins like Yoast and RankMath.',
  content = '<h2>WordPress for Programmatic SEO: The Complete Platform</h2><p>WordPress has evolved from a simple blogging platform into the most versatile content management system for programmatic SEO campaigns. With over 40% market share of the web, WordPress offers unmatched flexibility for creating, managing, and optimizing thousands of pages automatically.</p><h3>Programmatic SEO Capabilities</h3><p>WordPress excels in programmatic SEO through its extensive plugin ecosystem, custom post types, and database architecture. Create unlimited content variations using Advanced Custom Fields, WP All Import for bulk content creation, and SEO plugins for automated optimization.</p>',
  setup_guide = '<h3>WordPress Programmatic SEO Setup</h3><ol><li><strong>Choose Performance Hosting</strong> - Select managed WordPress hosting (WP Engine, Kinsta) for scalability</li><li><strong>Install Core Plugins</strong> - Add Yoast SEO, Advanced Custom Fields, WP All Import</li><li><strong>Create Custom Post Types</strong> - Define content structures for programmatic pages</li><li><strong>Set Up Data Sources</strong> - Connect APIs or prepare CSV files for bulk import</li><li><strong>Design Page Templates</strong> - Create flexible templates using ACF and custom fields</li><li><strong>Configure SEO Automation</strong> - Set up automated meta generation and schema markup</li><li><strong>Test and Deploy</strong> - Run small batches before full-scale deployment</li></ol>',
  screenshots = '[
    {"url": "/src/assets/screenshots/wordpress-dashboard.png", "title": "WordPress Admin Dashboard", "description": "Complete admin interface showing post editor, media library, and plugin management", "category": "Dashboard"},
    {"url": "/lovable-uploads/704ca633-1198-4152-87f0-dc67bd7139a4.png", "title": "SEO Plugin Integration", "description": "Yoast SEO plugin showing automated meta generation and optimization", "category": "SEO Tools"},
    {"url": "/lovable-uploads/704ca633-1198-4152-87f0-dc67bd7139a4.png", "title": "Custom Post Types", "description": "Advanced Custom Fields interface for programmatic content structure", "category": "Content Management"}
  ]'::jsonb,
  implementation_examples = '[
    {"title": "Custom Post Type Creation", "description": "Create custom post types for programmatic content", "code": "function create_programmatic_post_type() {\n    register_post_type(''programmatic_pages'', array(\n        ''public'' => true,\n        ''supports'' => array(''title'', ''editor'', ''custom-fields''),\n        ''show_in_rest'' => true\n    ));\n}\nadd_action(''init'', ''create_programmatic_post_type'');", "complexity": "Beginner", "timeEstimate": "15 minutes"},
    {"title": "Bulk Content Import", "description": "Import thousands of pages using WP All Import", "code": "// Configure WP All Import template\n$import_config = array(\n    ''post_type'' => ''programmatic_pages'',\n    ''post_status'' => ''publish'',\n    ''post_title'' => ''{title[1]}'',\n    ''post_content'' => ''{content[1]}'',\n    ''custom_fields'' => array(\n        ''seo_title'' => ''{seo_title[1]}'',\n        ''meta_description'' => ''{meta_desc[1]}''\n    )\n);", "complexity": "Intermediate", "timeEstimate": "30 minutes"}
  ]'::jsonb,
  support_resources = '{"documentation": "https://wordpress.org/documentation/", "tutorials": ["WordPress for Beginners", "Advanced Custom Fields Guide", "SEO Plugin Configuration"], "community": "https://wordpress.org/support/", "support": "https://wordpress.org/support/"}'::jsonb
WHERE slug = 'wordpress';