-- Update Webflow content
UPDATE software 
SET 
  description = 'Webflow combines visual design with powerful CMS capabilities, making it ideal for programmatic SEO campaigns that require custom design and automated content scaling. Built-in SEO tools, dynamic content management, and clean code generation ensure your programmatic pages rank well and load fast.',
  content = '<h2>Webflow: Visual Design Meets Programmatic SEO</h2><p>Webflow revolutionizes programmatic SEO by combining visual design capabilities with powerful content management features. Create stunning, SEO-optimized pages at scale without sacrificing design quality or technical performance.</p><h3>Dynamic Content Generation</h3><p>Webflow CMS enables automatic content population across template designs. Define content structures visually, then let the system generate hundreds of pages automatically with consistent styling and SEO optimization.</p>',
  setup_guide = '<h3>Webflow Programmatic SEO Setup</h3><ol><li><strong>Plan Content Structure</strong> - Define CMS collections and field relationships</li><li><strong>Design Master Templates</strong> - Create responsive layouts for programmatic content</li><li><strong>Set Up CMS Collections</strong> - Configure dynamic content with proper field types</li><li><strong>Configure SEO Settings</strong> - Set up automated meta fields and URL structures</li><li><strong>Import Content Data</strong> - Use CSV import or API integration for bulk content</li><li><strong>Test Responsive Design</strong> - Ensure templates work across all breakpoints</li><li><strong>Publish and Monitor</strong> - Deploy programmatic pages and track performance</li></ol>',
  screenshots = '[
    {"url": "/src/assets/screenshots/webflow-designer.png", "title": "Webflow Designer Interface", "description": "Visual design tools with CMS integration for programmatic content", "category": "Design Tools"},
    {"url": "/lovable-uploads/704ca633-1198-4152-87f0-dc67bd7139a4.png", "title": "CMS Collections", "description": "Dynamic content management for programmatic page generation", "category": "Content Management"},
    {"url": "/lovable-uploads/704ca633-1198-4152-87f0-dc67bd7139a4.png", "title": "SEO Settings", "description": "Built-in SEO controls for automated optimization", "category": "SEO Tools"}
  ]'::jsonb,
  implementation_examples = '[
    {"title": "CMS Collection Setup", "description": "Create dynamic content collections for programmatic pages", "code": "// Webflow CMS Collection Structure\n{\n  \"name\": \"Programmatic Pages\",\n  \"fields\": [\n    {\"name\": \"Title\", \"type\": \"text\", \"required\": true},\n    {\"name\": \"SEO Title\", \"type\": \"text\", \"limit\": 60},\n    {\"name\": \"Meta Description\", \"type\": \"text\", \"limit\": 160},\n    {\"name\": \"Content\", \"type\": \"rich-text\"},\n    {\"name\": \"Featured Image\", \"type\": \"image\"}\n  ]\n}", "complexity": "Beginner", "timeEstimate": "20 minutes"},
    {"title": "Dynamic Page Template", "description": "Create templates that automatically populate with CMS data", "code": "<!-- Webflow Template Structure -->\n<div class=\"page-wrapper\">\n  <h1 class=\"page-title\">{cms-field:title}</h1>\n  <div class=\"page-content\">{cms-field:content}</div>\n  <img src=\"{cms-field:featured-image}\" alt=\"{cms-field:title}\">\n</div>\n\n<!-- SEO Meta automatically generated -->\n<title>{cms-field:seo-title}</title>\n<meta name=\"description\" content=\"{cms-field:meta-description}\">", "complexity": "Intermediate", "timeEstimate": "45 minutes"}
  ]'::jsonb,
  support_resources = '{"documentation": "https://university.webflow.com/", "tutorials": ["Webflow CMS Guide", "Dynamic Content Creation", "SEO Best Practices"], "community": "https://forum.webflow.com/", "support": "https://webflow.com/support"}'::jsonb
WHERE slug = 'webflow';