-- Update Ahrefs content
UPDATE software 
SET 
  description = 'Ahrefs provides comprehensive SEO intelligence for programmatic campaigns with advanced keyword research, competitor analysis, and site auditing capabilities. Essential for identifying content opportunities, tracking performance across thousands of pages, and optimizing large-scale SEO strategies.',
  content = '<h2>Ahrefs: Intelligence Engine for Programmatic SEO</h2><p>Ahrefs provides the data foundation for successful programmatic SEO campaigns. From keyword research to performance tracking, Ahrefs ensures your programmatic content targets the right opportunities and achieves maximum visibility.</p><h3>Strategic Planning</h3><p>Use Keywords Explorer to identify thousands of long-tail keyword opportunities perfect for programmatic targeting. Content Gap analysis reveals what competitors are missing, providing clear direction for programmatic content creation.</p>',
  setup_guide = '<h3>Ahrefs for Programmatic SEO Setup</h3><ol><li><strong>Keyword Research</strong> - Use Keywords Explorer for programmatic opportunities</li><li><strong>Competitive Analysis</strong> - Analyze competitor programmatic strategies</li><li><strong>Content Planning</strong> - Map keywords to programmatic page templates</li><li><strong>Site Setup</strong> - Add your programmatic site to Ahrefs project</li><li><strong>Tracking Configuration</strong> - Set up keyword tracking for programmatic pages</li><li><strong>Site Audit</strong> - Run initial crawl to identify optimization opportunities</li><li><strong>API Integration</strong> - Connect Ahrefs data to content creation workflows</li><li><strong>Monitoring Dashboard</strong> - Create reports for programmatic SEO performance</li></ol>',
  screenshots = '[
    {"url": "/src/assets/screenshots/ahrefs-dashboard.png", "title": "Ahrefs Main Dashboard", "description": "Complete SEO analytics dashboard with keyword tracking and site audit results", "category": "Analytics"},
    {"url": "/lovable-uploads/704ca633-1198-4152-87f0-dc67bd7139a4.png", "title": "Keywords Explorer", "description": "Advanced keyword research tool for programmatic content planning", "category": "Research Tools"},
    {"url": "/lovable-uploads/704ca633-1198-4152-87f0-dc67bd7139a4.png", "title": "Site Audit Results", "description": "Technical SEO analysis for programmatic page optimization", "category": "SEO Analysis"}
  ]'::jsonb,
  implementation_examples = '[
    {"title": "Keyword Research Automation", "description": "Use Ahrefs API for programmatic keyword research", "code": "import requests\n\n# Ahrefs API integration\napi_key = \"your_ahrefs_api_key\"\nbase_url = \"https://apiv2.ahrefs.com\"\n\ndef get_keyword_ideas(seed_keyword, limit=1000):\n    params = {\n        \"token\": api_key,\n        \"target\": seed_keyword,\n        \"mode\": \"phrase\",\n        \"limit\": limit,\n        \"order_by\": \"volume:desc\"\n    }\n    \n    response = requests.get(f\"{base_url}/keywords-explorer\", params=params)\n    return response.json()", "complexity": "Advanced", "timeEstimate": "60 minutes"},
    {"title": "Site Audit Integration", "description": "Monitor programmatic pages with automated audits", "code": "# Ahrefs Site Audit API\ndef audit_programmatic_pages(domain):\n    audit_data = {\n        \"target\": domain,\n        \"token\": api_key,\n        \"mode\": \"domain\",\n        \"output\": \"json\"\n    }\n    \n    response = requests.post(f\"{base_url}/site-audit\", data=audit_data)\n    issues = response.json()[\"issues\"]\n    \n    # Filter for programmatic page issues\n    programmatic_issues = [issue for issue in issues \n                          if \"/programmatic/\" in issue[\"url\"]]\n    \n    return programmatic_issues", "complexity": "Intermediate", "timeEstimate": "45 minutes"}
  ]'::jsonb,
  support_resources = '{"documentation": "https://ahrefs.com/api/documentation", "tutorials": ["Ahrefs Academy", "API Integration Guide", "Programmatic SEO with Ahrefs"], "community": "https://ahrefs.com/community", "support": "https://help.ahrefs.com"}'::jsonb
WHERE slug = 'ahrefs';