
-- Add type field to software table to distinguish between software and tools
ALTER TABLE public.software ADD COLUMN type text NOT NULL DEFAULT 'software';

-- Add check constraint to ensure valid types
ALTER TABLE public.software ADD CONSTRAINT software_type_check CHECK (type IN ('software', 'tool'));

-- Update existing records to have proper types (assuming current ones are software)
UPDATE public.software SET type = 'software';

-- Insert sample software data (platforms like WordPress, Webflow, etc.)
INSERT INTO public.software (title, slug, description, category, type, is_featured, is_published, features, pricing_info, tags, demo_url, github_url) VALUES
('WordPress', 'wordpress', 'The world''s most popular content management system, perfect for programmatic SEO with thousands of plugins and themes.', 'CMS Platform', 'software', true, true, '[{"name": "Plugin Ecosystem", "description": "Access to 60,000+ plugins for any functionality"}, {"name": "SEO-Friendly", "description": "Built-in SEO optimization features and compatibility"}, {"name": "Scalable", "description": "Handles everything from small blogs to enterprise sites"}]', '{"free": true, "pricing_tiers": [{"name": "Free", "price": "$0", "features": ["Basic CMS", "Theme Support", "Plugin Support"]}, {"name": "Business", "price": "$25/month", "features": ["Premium Themes", "Advanced Plugins", "Priority Support"]}]}', '["CMS", "PHP", "MySQL", "Open Source"]', 'https://wordpress.org', 'https://github.com/WordPress/WordPress'),

('Webflow', 'webflow', 'Visual web design platform that generates clean, semantic HTML, CSS, and JavaScript for programmatic SEO sites.', 'Website Builder', 'software', true, true, '[{"name": "Visual Design", "description": "Design websites visually without coding"}, {"name": "CMS Integration", "description": "Built-in CMS for dynamic content management"}, {"name": "SEO Tools", "description": "Advanced SEO settings and optimization tools"}]', '{"free": false, "pricing_tiers": [{"name": "Basic", "price": "$12/month", "features": ["Visual Designer", "Basic CMS", "SSL Certificate"]}, {"name": "CMS", "price": "$16/month", "features": ["Advanced CMS", "Form Builder", "Site Search"]}]}', '["No-Code", "CMS", "Responsive Design"]', 'https://webflow.com', null),

('Next.js', 'nextjs', 'React framework for production-grade programmatic SEO applications with server-side rendering and static generation.', 'React Framework', 'software', false, true, '[{"name": "Server-Side Rendering", "description": "Built-in SSR for better SEO performance"}, {"name": "Static Site Generation", "description": "Generate static pages for maximum speed"}, {"name": "API Routes", "description": "Built-in API functionality for dynamic content"}]', '{"free": true, "pricing_tiers": [{"name": "Open Source", "price": "$0", "features": ["Full Framework", "Community Support", "All Features"]}]}', '["React", "SSR", "Static Generation", "JavaScript"]', 'https://nextjs.org', 'https://github.com/vercel/next.js');

-- Insert sample tools data (specific SEO tools)
INSERT INTO public.software (title, slug, description, category, type, is_featured, is_published, features, pricing_info, tags, demo_url, github_url) VALUES
('Screaming Frog SEO Spider', 'screaming-frog', 'Desktop program that crawls website URLs to audit and analyze technical and onsite SEO data.', 'SEO Crawler', 'tool', true, true, '[{"name": "Site Crawling", "description": "Crawl up to 500 URLs for free or unlimited with license"}, {"name": "Technical SEO Audit", "description": "Identify broken links, redirects, and technical issues"}, {"name": "Data Export", "description": "Export data to CSV, Excel, or Google Sheets"}]', '{"free": true, "pricing_tiers": [{"name": "Free", "price": "$0", "features": ["500 URL Crawl Limit", "Basic Features", "Community Support"]}, {"name": "Paid", "price": "$259/year", "features": ["Unlimited Crawling", "Advanced Features", "Priority Support"]}]}', '["SEO", "Crawler", "Technical SEO", "Desktop App"]', 'https://www.screamingfrog.co.uk/seo-spider/', null),

('Ahrefs', 'ahrefs', 'Comprehensive SEO toolset for keyword research, competitor analysis, and site auditing for programmatic SEO campaigns.', 'SEO Suite', 'tool', true, true, '[{"name": "Keyword Research", "description": "Discover profitable keywords with search volume data"}, {"name": "Competitor Analysis", "description": "Analyze competitor strategies and find opportunities"}, {"name": "Site Audit", "description": "Comprehensive technical SEO auditing"}]', '{"free": false, "pricing_tiers": [{"name": "Lite", "price": "$99/month", "features": ["Basic Keyword Research", "Site Audit", "Rank Tracker"]}, {"name": "Standard", "price": "$199/month", "features": ["Advanced Features", "Content Explorer", "Keyword Explorer"]}]}', '["SEO", "Keyword Research", "Competitor Analysis", "SaaS"]', 'https://ahrefs.com', null),

('Google Search Console', 'google-search-console', 'Free tool from Google to monitor and troubleshoot your website''s presence in Google Search results.', 'Search Analytics', 'tool', false, true, '[{"name": "Search Performance", "description": "Monitor clicks, impressions, and rankings"}, {"name": "Index Coverage", "description": "Check which pages are indexed by Google"}, {"name": "Core Web Vitals", "description": "Monitor page experience metrics"}]', '{"free": true, "pricing_tiers": [{"name": "Free", "price": "$0", "features": ["Search Analytics", "Index Monitoring", "Performance Insights"]}]}', '["Google", "Search Analytics", "Free Tool", "Performance"]', 'https://search.google.com/search-console', null),

('SEMrush', 'semrush', 'All-in-one digital marketing toolkit for programmatic SEO, PPC, content marketing, and competitive research.', 'SEO Suite', 'tool', false, true, '[{"name": "Keyword Magic Tool", "description": "Research keywords with advanced filtering options"}, {"name": "Position Tracking", "description": "Monitor keyword rankings across devices and locations"}, {"name": "Site Audit", "description": "Comprehensive technical and SEO site analysis"}]', '{"free": false, "pricing_tiers": [{"name": "Pro", "price": "$119.95/month", "features": ["Keyword Research", "Site Audit", "Position Tracking"]}, {"name": "Guru", "price": "$229.95/month", "features": ["Content Gap", "Historical Data", "Multi-target campaigns"]}]}', '["SEO", "Digital Marketing", "Keyword Research", "SaaS"]', 'https://semrush.com', null);
