// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvnovcnuqccxarjbnqil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2bm92Y251cWNjeGFyamJucWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTE3MTUsImV4cCI6MjA2Njc2NzcxNX0.Veoys8Ee4uEfIHNTafBqL1yAgjTCS6DsZR3gLYTXHHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);